version: "3.8"
services:
  web:
    image: nginx
    volumes:
      - ./hcaptcha.js:/usr/share/nginx/html/hcaptcha.js
      - ./matomo.js:/usr/share/nginx/html/matomo.js
      - ./index.html:/usr/share/nginx/html/index.html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    ports:
      - "80:80"
      - "443:443"